breakpoint_js_settings.admin_settings:
  title: 'Breakpoint javascript settings'
  description: 'Define breakpoint min width and device mappings.'
  route_name: breakpoint_js_settings.admin_settings
  parent: system.admin_config_media
