breakpoint_js_settings.admin_settings:
  path: '/admin/config/system/breakpoint_js'
  defaults:
    _form: '\Drupal\breakpoint_js_settings\Form\SettingsForm'
    _title: 'Breakpoint javascript settings'
  requirements:
    _permission: 'administer site configuration'
