language: php
dist: xenial

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - DRUPAL_TRAVIS_TEST_JAVASCRIPT=false
    - PATH="$PATH:$HOME/.composer/vendor/bin"

before_install:
  - composer global require thunder/travis

script:
  - test-drupal-module

notifications:
  email: false
