config_selector.feature.*:
  type: config_entity
  label: 'Configuration Selector Feature'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: label
      label: 'Description'

config_selector_third_party:
  type: mapping
  label: 'Schema for Configuration Selector additions to configuration entities'
  mapping:
    feature:
      type: string
      label: 'The Configuration Selector feature name'
    priority:
      type: integer
      label: 'The Configuration Selector feature priority'
    description:
      type: label
      label: 'Fallback description'

block.block.*.third_party.config_selector:
  type: config_selector_third_party

views.view.*.third_party.config_selector:
  type: config_selector_third_party
