entity.config_selector_feature.delete_form:
  path: '/admin/structure/config_selector/manage/{config_selector_feature}/delete'
  defaults:
    _entity_form: 'config_selector_feature.delete'
    _title: 'Delete Configuration Selector feature'
  requirements:
    _entity_access: 'config_selector_feature.delete'

entity.config_selector_feature.collection:
  path: '/admin/structure/config_selector'
  defaults:
    _entity_list: 'config_selector_feature'
    _title: 'Features'
  requirements:
    _custom_access: '\Drupal\config_selector\Plugin\Derivative\FeatureListMenuLink::access'
    _permission: 'administer site configuration'

config_select.feature.add:
  path: '/admin/structure/config_selector/add-feature'
  defaults:
    _entity_form: 'config_selector_feature.add'
    _title: 'Add Configuration Selector feature'
  requirements:
    _entity_create_access: 'config_selector_feature'

entity.config_selector_feature.edit_form:
  path: '/admin/structure/config_selector/manage/{config_selector_feature}/edit'
  defaults:
    _entity_form: 'config_selector_feature.edit'
    _title: 'Edit Configuration Selector feature'
  requirements:
    _entity_access: 'config_selector_feature.update'

entity.config_selector_feature.manage:
  path: '/admin/structure/config_selector/manage/{config_selector_feature}'
  defaults:
    _entity_form: 'config_selector_feature.default'
    _title: 'Manage Configuration Selector feature'
  requirements:
    _entity_access: 'config_selector_feature.manage'

config_selector.select:
  path: '/admin/structure/config_selector/switch/{config_selector_feature}/{config_entity_type}/{config_entity_id}/select}'
  defaults:
    _controller: '\Drupal\config_selector\Controller\Switcher::select'
    entity_type: 'config_selector_feature'
  requirements:
    _permission: 'administer site configuration'
    _csrf_token: 'TRUE'
