config_selector.admin_display:
  title: 'Configuration Selector features'
  parent: system.admin_structure
  description: 'Manage your Configuration Selector features.'
  route_name: entity.config_selector_feature.collection
  # Use a deriver so the link is only there if there are features to manage.
  deriver: '\Drupal\config_selector\Plugin\Derivative\FeatureListMenuLink'
