services:
  config_selector:
    class: Drupal\config_selector\ConfigSelector
    arguments: ['@config.factory', '@config.manager', '@entity_type.manager', '@logger.channel.config_selector', '@state']
  logger.channel.config_selector:
    parent: logger.channel_base
    arguments: ['config_selector']
  config_selector.active:
    class: Drupal\config_selector\ActiveEntity
    arguments: ['@entity_type.manager']
