breakpoint_js_settings.settings:
  type: config_object
  label: 'Breakpoint javascript settings'
  mapping:
    breakpoints:
      type: sequence
      label: 'Breakpoint definitions'
      sequence:
        type: mapping
        label: 'Breakpoint definition'
        mapping:
          breakpoint_id:
            type: string
            label: 'Breakpoint id'
          breakpoint_name:
            type: string
            label: 'Visible name'
          breakpoint_min_width:
            type: integer
            label: 'Min width'

    device_mappings:
      type: sequence
      label: 'Device Mappings'
      sequence:
        type: mapping
        label: 'Device Mapping'
        mapping:
          device:
            type: string
            label: 'Device type'
          breakpoint_id:
            type: string
            label: 'Breakpoint id'
