language: php
dist: xenial

php:
  - 7.2

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  matrix:
    - DRUPAL_TRAVIS_TEST_LOCATION="modules/contrib/scheduler_content_moderation_integration"
    - DRUPAL_TRAVIS_TEST_LOCATION="modules/contrib/scheduler"

  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin:$HOME/.config/composer/vendor/bin"
    - DRUPAL_TRAVIS_TEST_JAVASCRIPT=false

before_install:
  - composer global require thunder/travis
  - test-drupal-project prepare_build

  # required modules for scheduler tests.
  - composer require drupal/rules --no-update --working-dir=/tmp/test/scheduler_content_moderation_integration/install
  - composer require drupal/devel --no-update --working-dir=/tmp/test/scheduler_content_moderation_integration/install
  - composer require drupal/typed_data --no-update --working-dir=/tmp/test/scheduler_content_moderation_integration/install

script:
  - test-drupal-project
