language: node_js

sudo: false

node_js:
  - "node"

addons:
 apt:
  packages:
   - p7zip-full

env:
  global:
    - VERSION=$TRAVIS_TAG
    - VVERSION=v$VERSION
    - ZIP_FILENAME=shariff-$VERSION.zip
    - TAR_FILENAME=shariff-$VERSION.tar
    - TGZ_FILENAME=shariff-$VERSION.tar.gz

script:
  - npm run test

before_deploy:
  - echo "$TRAVIS_TAG / $VERSION / $VVERSION"
  - echo "$ZIP_FILENAME / $TAR_FILENAME / $TGZ_FILENAME"
  - npm run build
  - bash -c 'if [ ! -f $ZIP_FILENAME ]; then 7z a -tzip ${ZIP_FILENAME} ./dist/*; fi;'
  - bash -c 'if [ ! -f $TAR_FILENAME ]; then 7z a -ttar ${TAR_FILENAME} ./dist/*; fi;'
  - bash -c 'if [ ! -f $TGZ_FILENAME ]; then 7z a ${TGZ_FILENAME} ${TAR_FILENAME}; fi;'

deploy:
  - provider: releases
    api_key:
      secure: "QK+97CEzaL5FwA09hs7II9PnBKn1KRUUOLtmGnIw83FiqI5dUtAfPxe0WuA9dwIVX9FKOtPacn5nSoPb0LVvWwdTxGN2DOnYrUW8pIsPGng1Z5kbD2feJdTIeXkVmKb8JYssq76L7O6SyXQbkrbYq6KmrjFH9bEEpGlcUOyKY+k="
    file:
      - $ZIP_FILENAME
      - $TGZ_FILENAME
    skip_cleanup: true
    on:
      repo: heiseonline/shariff
      tags: true
  - provider: npm
    email: npmjs@heise.de
    api_key:
      secure: "hbiJOthZutV4G+4FidwK4XfDPPNXgdwWMeWjaFJueFdNwm5ifwnRl4CbSjPSW1os+0qRNF6HRFJbeRcZllqqQQfCSJB0fqB3AWFiSqvXzw+aJgO83EzEIxKSAD70/R+HME+ZX/JopBvFDe4mrsWGZk92kY2R/BS986yktIKGjJk="
    skip_cleanup: true
    on:
      repo: heiseonline/shariff
      tags: true
